name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "1.8.3"
  MOD_VERSION: "x.x.x"
  MOD_BUILD_STAGE: "prod"

permissions:
  contents: read

jobs:
  build-base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Poetry ${{env.POETRY_VERSION}}
        run: pipx install poetry==${{env.POETRY_VERSION}}

      - name: Setup Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --only main

      - name: Build base content pack
        run: poetry run python3 src/main.py

      - name: Get metadata
        run: |
          echo "MOD_VERSION=$(cat out/LATEST)" >> $GITHUB_ENV

      - name: Save base content pack
        uses: actions/upload-artifact@v4
        with:
          name: orientalmelon.baechusportraits-${{ env.MOD_VERSION }}-base
          path: out/orientalmelon.baechusportraits-*-base
          if-no-files-found: error

  build-sve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Poetry ${{env.POETRY_VERSION}}
        run: pipx install poetry==${{env.POETRY_VERSION}}

      - name: Setup Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --only main

      - name: Build SVE content pack
        run: poetry run python3 src/main.py -e SVE

      - name: Get metadata
        run: |
          echo "MOD_VERSION=$(cat out/LATEST)" >> $GITHUB_ENV

      - name: Save SVE content pack
        uses: actions/upload-artifact@v4
        with:
          name: orientalmelon.baechusportraits-${{ env.MOD_VERSION }}-base-sve
          path: out/orientalmelon.baechusportraits-*-base-sve
          if-no-files-found: error
