name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.12"
      MOD_VERSION: "0.0.0"
      MOD_ID: "unknown"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Build Content Pack
        run: uvx svpbuild

      - name: Get Metadata
        run: |
          MOD_VERSION=$(jq -r .Version manifest.json)
          MOD_ID=$(jq -r .UniqueID manifest.json)
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
          echo "MOD_ID=$MOD_ID" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MOD_ID }}-${{ env.MOD_VERSION }}
          path: build/out/${{ env.MOD_ID }}-${{ env.MOD_VERSION }}
          if-no-files-found: error
